//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTempMonitor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class templogEntities : DbContext
    {
        public templogEntities()
            : base("name=templogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<templog> templogs { get; set; }
    
        public virtual ObjectResult<TempsForRange_Result> TempsForRange(Nullable<int> hourRange)
        {
            var hourRangeParameter = hourRange.HasValue ?
                new ObjectParameter("hourRange", hourRange) :
                new ObjectParameter("hourRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TempsForRange_Result>("TempsForRange", hourRangeParameter);
        }
    }
}
